<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <AssemblyName>SplitTea.Lambda</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="JwtVerifier.fs" />
    <Compile Include="EventRepository.fs" />
    <Compile Include="Handler.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.2" />
    <ProjectReference Include="../SplitTea.Core/SplitTea.Core.fsproj" />
  </ItemGroup>
</Project>
