<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Infrastructure/DevMode.fs" />
    <Compile Include="Infrastructure/SupabaseClient.fs" />
    <Compile Include="Infrastructure/Auth.fs" />
    <Compile Include="Infrastructure/IndexedDb.fs" />
    <Compile Include="Infrastructure/SupabaseSync.fs" />
    <Compile Include="Infrastructure/FxRates.fs" />
    <Compile Include="Application/Storage.fs" />
    <Compile Include="Application/Commands.fs" />
    <Compile Include="Application/DevBootstrap.fs" />
    <Compile Include="Application/Sync.fs" />
    <Compile Include="UI/Types.fs" />
    <Compile Include="UI/Styles.fs" />
    <Compile Include="UI/Icons.fs" />
    <Compile Include="UI/Pages/Space.fs" />
    <Compile Include="UI/Pages/Analytics.fs" />
    <Compile Include="UI/Pages/Profile.fs" />
    <Compile Include="UI/Pages/ExpenseForm.fs" />
    <Compile Include="UI/Pages/SettlementForm.fs" />
    <Compile Include="UI/Program.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.3.0" />
    <PackageReference Include="Fable.React" Version="9.4.0" />
    <PackageReference Include="Feliz" Version="2.9.0" />
    <PackageReference Include="Fable.Elmish" Version="4.4.0" />
    <PackageReference Include="Fable.Elmish.React" Version="4.0.0" />
    <PackageReference Include="Thoth.Json" Version="10.5.0" />
    <ProjectReference Include="../SplitTea.Core/SplitTea.Core.fsproj" />
  </ItemGroup>
</Project>
